/**
 * Generate the repository metrics blocks in PROJECT_SUMMARY.md and
 * docs/CURRENT_ARCHITECTURE.md.
 *
 *   node scripts/repo-metrics.mjs           # rewrite the blocks
 *   node scripts/repo-metrics.mjs --check   # fail if a block is stale
 *
 * These numbers were previously hand-written, and drifted badly: the summary
 * claimed 3 migrations when there were 11, and 34 routes when there were 42.
 * A number a human has to remember to update is a number that will be wrong,
 * so it is derived from the tree instead.
 *
 * Counts are static (parsed from source), not produced by running the suite —
 * cheap enough to run on every docs change, and exact for routes, suites and
 * migrations. The test count counts `it(...)`/`test(...)` declarations, so a
 * suite that generates cases in a loop contributes one per declaration rather
 * than one per executed case — hence "declared test cases".
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const BACKEND = join(dirname(fileURLToPath(import.meta.url)), "..");
const ROOT = join(BACKEND, "..");

const read = (p) => readFileSync(p, "utf8");
const listDir = (p) => {
  try {
    return readdirSync(p);
  } catch {
    return [];
  }
};

const testFiles = listDir(join(BACKEND, "tests")).filter((f) => f.endsWith(".test.ts"));
const testCount = testFiles.reduce((n, f) => {
  const src = read(join(BACKEND, "tests", f));
  return n + (src.match(/^\s*(?:it|test)(?:\.\w+)?\s*\(/gm) ?? []).length;
}, 0);

const migrations = listDir(join(BACKEND, "src", "db", "migrations")).filter((f) =>
  f.endsWith(".sql"),
);

const apiDir = join(BACKEND, "src", "api");
const routes = new Set();
for (const file of listDir(apiDir).filter((f) => f.endsWith(".ts"))) {
  const src = read(join(apiDir, file));
  for (const m of src.matchAll(/\.(get|post|put|patch|delete)\("([^"]+)"/g)) {
    routes.add(`${m[1].toUpperCase()} ${m[2]}`);
  }
}

const countSourceFiles = (dir) => {
  let n = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === "dist") continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) n += countSourceFiles(full);
    else if (entry.name.endsWith(".ts")) n += 1;
  }
  return n;
};

const metrics = {
  tests: testCount,
  suites: testFiles.length,
  routes: routes.size,
  migrations: migrations.length,
  sourceFiles: countSourceFiles(join(BACKEND, "src")),
};

const GENERATED = "generated by backend/scripts/repo-metrics.mjs — do not edit by hand";

const bulletBlock = [
  `<!-- METRICS:START (${GENERATED}) -->`,
  `- **${metrics.tests} declared test cases** across ${metrics.suites} suites, all passing; strict-mode TypeScript`,
  `- **${metrics.routes} HTTP routes** (market, auth, live/demo paper trading, settings, bot, legacy/admin)`,
  `- **${metrics.migrations} forward-only Postgres migrations**, shared by production and local tests`,
  `- **${metrics.sourceFiles} backend TypeScript source files**`,
  "<!-- METRICS:END -->",
].join("\n");

/** One line of prose, for docs that mention the counts in passing. */
const inlineBlock = [
  `<!-- METRICS:INLINE:START (${GENERATED}) -->`,
  `Verified counts: ${metrics.routes} HTTP routes, ${metrics.migrations} forward-only migrations, ` +
    `${metrics.suites} test files / ${metrics.tests} declared test cases, all passing.`,
  "<!-- METRICS:INLINE:END -->",
].join("\n");

const targets = [
  { file: "PROJECT_SUMMARY.md", marker: "METRICS", body: bulletBlock },
  { file: "docs/CURRENT_ARCHITECTURE.md", marker: "METRICS:INLINE", body: inlineBlock },
];

const checking = process.argv.includes("--check");
let stale = false;

for (const target of targets) {
  const path = join(ROOT, target.file);
  const current = read(path);
  // Normalize line endings so a CRLF checkout does not read as permanently stale.
  const normalized = current.replace(/\r\n/g, "\n");
  const pattern = new RegExp(`<!-- ${target.marker}:START[\\s\\S]*?<!-- ${target.marker}:END -->`);

  if (!pattern.test(normalized)) {
    console.error(
      `${target.file} has no ${target.marker} block. Add the markers first:\n` +
        `<!-- ${target.marker}:START --> ... <!-- ${target.marker}:END -->`,
    );
    process.exit(1);
  }

  const updated = normalized.replace(pattern, target.body);
  if (updated === normalized) continue;

  if (checking) {
    console.error(`${target.file} metrics are stale. Run: npm run docs:metrics`);
    stale = true;
  } else {
    writeFileSync(path, updated);
    console.log(`${target.file} metrics updated`);
  }
}

if (checking && stale) process.exit(1);
console.log(checking ? "metrics up to date" : "metrics generated", metrics);
